-- leaflogger-py schema (SQLite). Single user: no users/loginlog/evstatus tables,
-- no leaflogs_user_id / trips_users_id columns. All log columns NULL-able:
-- the LeafSpy CSV leaves many empty and the importer stores them as NULL.
-- Source of truth for column set: ../leaflogger/sql/schema.sql
CREATE TABLE IF NOT EXISTS logs (
  leaflogs_id INTEGER PRIMARY KEY AUTOINCREMENT,
  leaflogs_ignore INTEGER NULL,
  leaflogs_elevation_checked INTEGER NULL,
  leaflogs_timestamp TEXT NULL,
  leaflogs_lat REAL NULL,
  leaflogs_lon REAL NULL,
  leaflogs_elevation INTEGER NULL,
  leaflogs_elevation_lookedup REAL NULL,
  leaflogs_speed INTEGER NULL,
  leaflogs_gids INTEGER NULL,
  leaflogs_soc INTEGER NULL,
  leaflogs_ahr INTEGER NULL,
  leaflogs_pack_volts REAL NULL,
  leaflogs_pack_amps REAL NULL,
  leaflogs_max_cp_mv INTEGER NULL,
  leaflogs_min_cp_mv INTEGER NULL,
  leaflogs_avg_cp_mv INTEGER NULL,
  leaflogs_cp_mv_diff INTEGER NULL,
  leaflogs_judgement_value INTEGER NULL,
  leaflogs_pack_t1_f REAL NULL,
  leaflogs_pack_t1_c REAL NULL,
  leaflogs_pack_t2_f REAL NULL,
  leaflogs_pack_t2_c REAL NULL,
  leaflogs_pack_t3_f REAL NULL,
  leaflogs_pack_t3_c REAL NULL,
  leaflogs_pack_t4_f REAL NULL,
  leaflogs_pack_t4_c REAL NULL,
  leaflogs_cp01 INTEGER NULL,
  leaflogs_cp02 INTEGER NULL,
  leaflogs_cp03 INTEGER NULL,
  leaflogs_cp04 INTEGER NULL,
  leaflogs_cp05 INTEGER NULL,
  leaflogs_cp06 INTEGER NULL,
  leaflogs_cp07 INTEGER NULL,
  leaflogs_cp08 INTEGER NULL,
  leaflogs_cp09 INTEGER NULL,
  leaflogs_cp10 INTEGER NULL,
  leaflogs_cp11 INTEGER NULL,
  leaflogs_cp12 INTEGER NULL,
  leaflogs_cp13 INTEGER NULL,
  leaflogs_cp14 INTEGER NULL,
  leaflogs_cp15 INTEGER NULL,
  leaflogs_cp16 INTEGER NULL,
  leaflogs_cp17 INTEGER NULL,
  leaflogs_cp18 INTEGER NULL,
  leaflogs_cp19 INTEGER NULL,
  leaflogs_cp20 INTEGER NULL,
  leaflogs_cp21 INTEGER NULL,
  leaflogs_cp22 INTEGER NULL,
  leaflogs_cp23 INTEGER NULL,
  leaflogs_cp24 INTEGER NULL,
  leaflogs_cp25 INTEGER NULL,
  leaflogs_cp26 INTEGER NULL,
  leaflogs_cp27 INTEGER NULL,
  leaflogs_cp28 INTEGER NULL,
  leaflogs_cp29 INTEGER NULL,
  leaflogs_cp30 INTEGER NULL,
  leaflogs_cp31 INTEGER NULL,
  leaflogs_cp32 INTEGER NULL,
  leaflogs_cp33 INTEGER NULL,
  leaflogs_cp34 INTEGER NULL,
  leaflogs_cp35 INTEGER NULL,
  leaflogs_cp36 INTEGER NULL,
  leaflogs_cp37 INTEGER NULL,
  leaflogs_cp38 INTEGER NULL,
  leaflogs_cp39 INTEGER NULL,
  leaflogs_cp40 INTEGER NULL,
  leaflogs_cp41 INTEGER NULL,
  leaflogs_cp42 INTEGER NULL,
  leaflogs_cp43 INTEGER NULL,
  leaflogs_cp44 INTEGER NULL,
  leaflogs_cp45 INTEGER NULL,
  leaflogs_cp46 INTEGER NULL,
  leaflogs_cp47 INTEGER NULL,
  leaflogs_cp48 INTEGER NULL,
  leaflogs_cp49 INTEGER NULL,
  leaflogs_cp50 INTEGER NULL,
  leaflogs_cp51 INTEGER NULL,
  leaflogs_cp52 INTEGER NULL,
  leaflogs_cp53 INTEGER NULL,
  leaflogs_cp54 INTEGER NULL,
  leaflogs_cp55 INTEGER NULL,
  leaflogs_cp56 INTEGER NULL,
  leaflogs_cp57 INTEGER NULL,
  leaflogs_cp58 INTEGER NULL,
  leaflogs_cp59 INTEGER NULL,
  leaflogs_cp60 INTEGER NULL,
  leaflogs_cp61 INTEGER NULL,
  leaflogs_cp62 INTEGER NULL,
  leaflogs_cp63 INTEGER NULL,
  leaflogs_cp64 INTEGER NULL,
  leaflogs_cp65 INTEGER NULL,
  leaflogs_cp66 INTEGER NULL,
  leaflogs_cp67 INTEGER NULL,
  leaflogs_cp68 INTEGER NULL,
  leaflogs_cp69 INTEGER NULL,
  leaflogs_cp70 INTEGER NULL,
  leaflogs_cp71 INTEGER NULL,
  leaflogs_cp72 INTEGER NULL,
  leaflogs_cp73 INTEGER NULL,
  leaflogs_cp74 INTEGER NULL,
  leaflogs_cp75 INTEGER NULL,
  leaflogs_cp76 INTEGER NULL,
  leaflogs_cp77 INTEGER NULL,
  leaflogs_cp78 INTEGER NULL,
  leaflogs_cp79 INTEGER NULL,
  leaflogs_cp80 INTEGER NULL,
  leaflogs_cp81 INTEGER NULL,
  leaflogs_cp82 INTEGER NULL,
  leaflogs_cp83 INTEGER NULL,
  leaflogs_cp84 INTEGER NULL,
  leaflogs_cp85 INTEGER NULL,
  leaflogs_cp86 INTEGER NULL,
  leaflogs_cp87 INTEGER NULL,
  leaflogs_cp88 INTEGER NULL,
  leaflogs_cp89 INTEGER NULL,
  leaflogs_cp90 INTEGER NULL,
  leaflogs_cp91 INTEGER NULL,
  leaflogs_cp92 INTEGER NULL,
  leaflogs_cp93 INTEGER NULL,
  leaflogs_cp94 INTEGER NULL,
  leaflogs_cp95 INTEGER NULL,
  leaflogs_cp96 INTEGER NULL,
  leaflogs_batvolt REAL NULL,
  leaflogs_vin TEXT NULL,
  leaflogs_health REAL NULL,
  leaflogs_raw_12_batt REAL NULL,
  leaflogs_odometer INTEGER NULL,
  leaflogs_qc INTEGER NULL,
  leaflogs_l1l2 INTEGER NULL,
  leaflogs_tp_fl REAL NULL,
  leaflogs_tp_fr REAL NULL,
  leaflogs_tp_rr REAL NULL,
  leaflogs_tp_rl REAL NULL,
  leaflogs_ambient INTEGER NULL,
  leaflogs_soh INTEGER NULL,
  leaflogs_regen INTEGER NULL,
  leaflogs_epoch INTEGER NULL,
  leaflogs_android_batt INTEGER NULL,
  leaflogs_power_motor INTEGER NULL,
  leaflogs_power_aux INTEGER NULL,
  leaflogs_power_ac INTEGER NULL,
  leaflogs_psi_ac_compressor INTEGER NULL,
  leaflogs_est_power_ac INTEGER NULL,
  leaflogs_est_power_heater INTEGER NULL,
  leaflogs_plug_state INTEGER NULL,
  leaflogs_charge_mode INTEGER NULL,
  leaflogs_onboard_charger_power INTEGER NULL,
  leaflogs_drive_mode INTEGER NULL,
  leaflogs_hvolt1 REAL NULL,
  leaflogs_hvolt2 REAL NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_logs_timestamp ON logs(leaflogs_timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_lat ON logs(leaflogs_lat);
CREATE INDEX IF NOT EXISTS idx_logs_lon ON logs(leaflogs_lon);
CREATE INDEX IF NOT EXISTS idx_logs_ignore ON logs(leaflogs_ignore);

CREATE TABLE IF NOT EXISTS trips (
  trips_id INTEGER PRIMARY KEY AUTOINCREMENT,
  trips_name TEXT NOT NULL DEFAULT '',
  trips_datetime_start TEXT NOT NULL,
  trips_datetime_end TEXT NOT NULL
);
